### ISSUE TITLE
Add support to make yarn usable in setup field

### ISSUE THREAD

**Issue by imbsky** [JasonEtco/build-and-tag-action#3]
```console
/usr/bin/yarn --frozen-lockfile && yarn build
yarn run v1.22.4
error Command "&&" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
##[error]The process '/usr/bin/yarn' failed with exit code 1
✖  fatal     Error: The process '/usr/bin/yarn' failed with exit code 1 
    at ExecState._setResult (/home/runner/work/_actions/JasonEtco/build-and-tag-action/v1/dist/index.js:16755:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/JasonEtco/build-and-tag-action/v1/dist/index.js:16738:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/JasonEtco/build-and-tag-action/v1/dist/index.js:16632:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Comment by JasonEtco** [comment]
Can you share your whole workflow file? This isn’t a problem with yarn.

**Comment by imbsky** [comment]
This doesn't work.

```yml
- name: Publish action
  uses: JasonEtco/build-and-tag-action@v1
  with:
    setup: "yarn --frozen-lockfile && yarn build"
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by JasonEtco** [comment]
That’s not your whole workflow file. Please share the entire file or I can’t help you.

**Comment by imbsky** [comment]
The problem is probably due to Node.js specific unique behavior due to the lack of yarn subcommands, so I don't think the entire workflow is necessary. Anyway, I updated that.

**Comment by JasonEtco** [comment]
There's currently a problem with `@actions/exec` and multiple commands (using `&&`), see #4 and https://github.com/actions/toolkit/issues/461. Still, this sounds like something different - but also not something that this action is doing wrong. I'm going to close this because there's nothing we can do here.

**Comment by imbsky** [comment]
Indeed.
