### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by say8425** [JasonEtco/build-and-tag-action#40]
```
Run JasonEtco/build-and-tag-action@v2
  with:
  env:
    GITHUB_TOKEN: ***
ℹ  info      Updating tag [v1.0.5]
ℹ  info      Creating tree
Error: Resource not accessible by integration
✖  fatal     HttpError: Resource not accessible by integration 
    at /home/runner/work/_actions/JasonEtco/build-and-tag-action/v2/dist/index.js:4476:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.createCommit [as default] (/home/runner/work/_actions/JasonEtco/build-and-tag-action/v2/dist/index.js:17383:18)
    at async buildAndTagAction (/home/runner/work/_actions/JasonEtco/build-and-tag-action/v2/dist/index.js:17492:20)
```

Action looks failed to connect to GitHub API.
https://github.com/say8425/bump-test/actions/runs/4595276424/jobs/8115347070#step:5:8

**Comment by rspurgeon** [comment]
I'm also receiving this error

**Comment by say8425** [comment]
Thanks! This made works 👍
